start_bot_development:
	/Users/ilkedelandcaglar/.conda/envs/tradee/bin/python -i s_admin.py;

#           bot = udentify_bot()
#        	bot.login ()
#           bot.select_firm("Under Armour","Akasya")


#driver.find_element(By.ID, 'EntraceCountChart')

#bot.driver.find_element(By.ID, 'EntraceCountChart')

##bot.driver.find_element_by_name('EntraceCountChart')

##bot.driver.find_element_by_class_name("EntraceCountChart")

#element = bot.driver.find_element_by_class_name("EntraceCountChart")
#element.screenshot ( f"/Users/ilkedelandcaglar/Downloads/udentify/bot_udentify/requests/elma.png" )